import api from './api'

export const adminService = {
  getDashboardStats: () => api.get('/admin/dashboard'),
  getUsers: (params) => api.get('/admin/users', { params }),
  getUserById: (id) => api.get(`/admin/users/${id}`),
  updateUser: (id, data) => api.put(`/admin/users/${id}`, data),
  deactivateUser: (id) => api.patch(`/admin/users/${id}/deactivate`),
  activateUser: (id) => api.patch(`/admin/users/${id}/activate`),
  getCompanies: (params) => api.get('/admin/companies', { params }),
  getCompanyById: (id) => api.get(`/admin/companies/${id}`),
  updateCompanyStatus: (id, status) => api.patch(`/admin/companies/${id}/status`, { status }),
  checkCompanyDuplicates: (id) => api.get(`/admin/companies/${id}/duplicate-check`),
  getCompanyAuditLog: (id) => api.get(`/admin/companies/${id}/audit-log`),
  markCompanyUnderReview: (id, reason) => api.patch(`/admin/companies/${id}/under-review`, { reason }),
  verifyCompany: (id, reason) => api.patch(`/admin/companies/${id}/verify`, { reason }),
  rejectCompany: (id, reason) => api.patch(`/admin/companies/${id}/reject`, { reason }),
  markCompanyDuplicate: (id, payload) => api.patch(`/admin/companies/${id}/mark-duplicate`, payload),
  restoreCompany: (id, payload) => api.patch(`/admin/companies/${id}/restore`, payload),
  getJobs: (params) => api.get('/admin/jobs', { params }),
  updateJobStatus: (id, status) => api.patch(`/admin/jobs/${id}/status`, { status }),
  getAnalytics: (range) => api.get('/admin/analytics', { params: { range } }),
  getRevenue: (range) => api.get('/admin/revenue', { params: { range } }),
  getReports: (type, range) => api.get('/admin/reports', { params: { type, range } }),
}
