const router = require('express').Router()
const { authenticate } = require('../middleware/auth')
const { requireRole } = require('../middleware/role')
const ctrl = require('../controllers/admin.controller')

router.use(authenticate)
router.use(requireRole('admin'))

router.get('/dashboard', ctrl.getDashboardStats)
router.get('/users', ctrl.getUsers)
router.get('/users/:id', ctrl.getUserById)
router.put('/users/:id', ctrl.updateUser)
router.patch('/users/:id/deactivate', ctrl.deactivateUser)
router.patch('/users/:id/activate', ctrl.activateUser)
router.get('/companies', ctrl.getCompanies)
router.get('/companies/:id', ctrl.getCompanyById)
router.get('/companies/:id/duplicate-check', ctrl.getCompanyDuplicateCheck)
router.get('/companies/:id/audit-log', ctrl.getCompanyAuditLog)
router.patch('/companies/:id/status', ctrl.updateCompanyStatus)
router.patch('/companies/:id/under-review', ctrl.markCompanyUnderReview)
router.patch('/companies/:id/verify', ctrl.verifyCompany)
router.patch('/companies/:id/reject', ctrl.rejectCompany)
router.patch('/companies/:id/mark-duplicate', ctrl.markCompanyDuplicate)
router.patch('/companies/:id/restore', ctrl.restoreCompany)
router.get('/jobs', ctrl.getAdminJobs)
router.patch('/jobs/:id/status', ctrl.updateJobStatus)
router.get('/analytics', ctrl.getAnalytics)
router.get('/revenue', ctrl.getRevenue)
router.get('/reports', ctrl.getReports)

module.exports = router
